### ISSUE TITLE
Syntax error on except lines?

### ISSUE THREAD

**Issue by benpilletspoken** [zauberpony/ansible-mysql-query#8]
👏  for maintaining this.
I may be missing something, but I think the syntax here isn't right. `https://github.com/zauberpony/ansible-mysql-query/blob/v0.1/library/mysql_query#L106`

Isn't it supposed to be:
```except MySQLdb.ProgrammingError as e:```
with `as` instead of a comma?

I'm running on CentOS 7 and Mac OS X with python 3.6.3.

**Comment by benpilletspoken** [comment]
Gah.  blarg.  `http://python3porting.com/noconv.html#handling-exceptions` . This is so nasty.  Why do I have a feeling folks are still using Python 2.5 somewhere out in the wild.  Are you open to switching to newer syntax that is >= 2.6 compatible?

**Comment by zauberpony** [comment]
Hi Ben,

Well, now that [Ansible 2.4 requires python >= 2.6](https://www.ansible.com/blog/using-ansible-to-manage-rhel-5-yesterday-today-and-tomorrow) it's sensible to drop 2.4 support in favour of python 3.x compatibility.

So, what's exactly your issue with the syntax (I'm just asking for my understanding), are you running this code on a node with python 3 only? Or did you come accross the issue while testing/developing locally?

Feel free to open a PR, otherwise I'll have a look at this code to make it python3 compatible (or apply the same coding standards as for the ansible core).

**Comment by benpilletspoken** [comment]
Interesting.  It looks like python2.7 is ok with the syntax.  Here's the results I get:
```
ben.pillet@BenPillet-MacBook-Pro ~/github/zauberpony/ansible-mysql-query
$ python2.7 -m py_compile library/mysql_query ; echo $?
0
ben.pillet@BenPillet-MacBook-Pro ~/github/zauberpony/ansible-mysql-query
$ python3.6 -m py_compile library/mysql_query ; echo $?
  File "library/mysql_query", line 106
    except MySQLdb.ProgrammingError, e:
                                   ^
SyntaxError: invalid syntax
1
```

I'll open a PR in a sec 👍

**Comment by zauberpony** [comment]
yeah, the `except xyz, e` is python 2 syntax, and `as e` is python 3 syntax, which has been [backported to python 2.6](https://docs.python.org/2/whatsnew/2.6.html), so the same python code can work both with python 2 and 3.
